"""Regenerate the root README.md from every section's README.

Run after adding or changing a section:  python3 build_readme.py
"""

import re
from pathlib import Path

ROOT = Path(__file__).parent
ORDER = [
    "sliding_window", "prefix_sums", "binary_search", "stacks_heaps",
    "binary_trees", "binary_search_trees", "tries", "backtracking",
    "graphs", "dynamic_programming", "math_algorithms",
]
HELPERS = {"tree.py", "bst.py"}  # shared utilities, not techniques


def parse(folder):
    text = (ROOT / folder / "README.md").read_text()
    title = re.search(r"^# (.+)$", text, re.M).group(1)
    guide = re.search(r"\[[^\]]*Field Guide\]\((https://[^)]+)\)", text).group(1)
    lines = text.splitlines()
    start = next(i for i, l in enumerate(lines) if l.startswith("|"))
    end = next((i for i in range(start, len(lines)) if not lines[i].startswith("|")), len(lines))
    def relink(m):  # links are relative to the section folder; make them root-relative
        target = m.group(1)
        if target.startswith(("http:", "https:", "#")):
            return m.group(0)
        return "](" + (target[3:] if target.startswith("../") else f"{folder}/{target}") + ")"

    table = [re.sub(r"\]\(([^)]+)\)", relink, line) for line in lines[start:end]]
    files = [p for p in (ROOT / folder).glob("*.py") if p.name not in HELPERS]
    tests = sum(len(re.findall(r"^def test_", p.read_text(), re.M)) for p in (ROOT / folder).glob("*.py"))
    return title, guide, table, len(files), tests


def main():
    sections = [(f, *parse(f)) for f in ORDER]
    total_t = sum(s[4] for s in sections)
    total_k = sum(s[5] for s in sections)
    out = [
        "# DSA Grand Slam",
        "",
        "One folder per theme, one file per technique: implementation + tests checked "
        "against brute force. Each theme has a Field Guide explaining every technique.",
        "",
        "```",
        "python3 graphs/dijkstra.py                                              # one file",
        'for f in */*.py; do python3 "$f" >/dev/null || echo "FAIL $f"; done   # everything',
        "```",
        "",
        "| Theme | Techniques | Tests | Field Guide |",
        "|---|---|---|---|",
    ]
    for folder, title, guide, _, n, tests in sections:
        out.append(f"| [{title}]({folder}/) | {n} | {tests} | [Guide]({guide}) |")
    out.append(f"| **Total** | **{total_t}** | **{total_k}** | |")
    out += ["", "## By situation", ""]
    for folder, title, guide, table, _, _ in sections:
        out += [f"<details><summary><b>{title}</b></summary>", "", *table, "", "</details>", ""]
    out.append("Generated by `python3 build_readme.py` from the section READMEs — edit those, not this.")
    (ROOT / "README.md").write_text("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
